# Generated by Django 5.1.5 on 2025-01-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopback', '0003_customer_remove_cart_user_cart_worker_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
